version: 2.1

jobs:
  build:
    docker:
      - image circleci/python:3.8.3
    steps:
        - checkout
        -run:
          name: Install package
          command: |
            pip install pandas
            pip install .
        - run:
          name: Run Tests
          command: |
            python -m unittest
